[package]
name = "crabbybuddy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
# llama-cpp-2 = { version = "0.1.151", features = ["cuda"] } #can use vulkan
llama-cpp-2 = "0.1.151"
rand = "0.9.2"
rustyline = "18.0.1"

[profile.release]
opt-level = "s" #3 for speed, "z" for size
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

# RUSTFLAGS="-C target-cpu=native -C force-frame-pointers=no" cargo build --release
